package com.cucumbercraft.pages;

import com.cucumbercraft.stepdefinitions.BookFiveStarData;
import com.cucumbercraft.stepdefinitions.CancelFivestarData;
import com.cucumbercraft.stepdefinitions.CommonMethods;
import com.cucumbercraft.stepdefinitions.CreditCard;
import com.cucumbercraft.stepdefinitions.EditFiveStarData;
import com.cucumbercraft.stepdefinitions.MasterStepDefination;

public class Variables extends MasterStepDefination {

	public static boolean TransferRefundflag=false;
	public static boolean TRefundflag=false;
	public static boolean Taxflag=false;
	public static boolean Refundflag=false;
	public static boolean Paymentflag=false;
	public static boolean Transportationflag=false;
	public static boolean popupstatus=false;
	public static boolean CKflag=false;
	public static boolean Promoflag=false;
	public static boolean Agencyflag=false;
	public static boolean Cancelflag=false;
	public static boolean Bookingflag=false;
	public static boolean PromoAmountfulluse=false;
	public static boolean additionalserviceflag=false;
	 	public static String ReqNo=new String();
	 	public static String pnrNumber=new String();
	 	public static String ReqSource = new String();
	 	public static String[] arrFirstName = null;
	 	public static  String[] arrLastName = null;
	 	public static  String[] arrPsngrType = null;
	 	public static String PsngrType=null;
	 	public static String selectadd=null;
	 	public static String Promocode=null;
	 	public static String TotalAdditionalServices=null;
	 	public static  String[] arrPrimFlag = null;
		 public static boolean Editflag=false;
	 	public static  String[] arrServiceType=null;
	 	public static  String[] arrPromoCertificateID=null;
	 	public static  String[] arrPromocode = null;
	 	public static  String[] arrselectadd = null;
	 	public static  String[] arrDateInterval = null;
	 	public static  String[] arrTimeInterval = null;
		public static String RefundAmt=null;
	 	public static  String[] arrAirportCode=null;
		public static String AirportCode=null;
	 	public static  int count=0;
	 	public static String AirportCodeAdditionService=null;
	 	public static String ServiceTypeAdditionService=null;
	 	public static String PriceperBookingAdditionService=null;
	 	public static String AdultPriceAdditionService=null;
	 	public static String ChildPriceAdditionService=null;
		public static String[] arrDiscountdoller=null;
		public static String[] arrDiscountpercent=null;
	 	public static  String EmailCheckBox=new String();
	 	public static  String EmailAddress=new String();
	 	public static  String ProfileID=new String();
	 	public static  String CardFirstName=new String();
	 	public static  String CardLastName=new String();
	 	public static  String CardNumber=new String();
	 	public static  String CardExpMonth=new String();
	 	public static  String CardExpYear=new String();
	    public static String[] arrSRCancelledBookingStatus=null;
	 	public static   String BookPriority=new String();
	 	public static   String TransferRefundPNRNo=new String();
	 	public static   String TransferRefundReqNo=new String();
	 	public static   double NetTotalAmt;
	 	public static   double NetAdultPrice;
		public static   double PromoDiscount;
		public static double OutstandingAmt;
		public static String[] arrOutstandingAmt=null;
		public static   String OldReqNo = new String();
		public static   String[] arrAirportPrice=null;
		public static   String[] arrNetTotalAmt=null;
		public static  	String[] arrSRBookingStatus=null;
		public static  	String SRBookingStatus=null;
		public static String BookingTabName;
		public static String AdminTabName;
		public static String RefundTabName;
		public static String SRdetailsTabName;
		public static String FlightdetailsTabName;
		public static String BookingStatus;
		public static String TransferRefundAmt;
		public static String UpdatedBookingStatus;
		public static String[] arrCancelledSRStatus;
		public static String CardNum = null;
		public static String AADVNum = null;
		public static String OnewordId = null;		
		//public static String NetTotalAmt;
		static BookFiveStarData BookFivestardata;
		static EditFiveStarData Editfivestardata;
		static CancelFivestarData CancelBookingdata;
		static CreditCard Creditcarddata;
		
		public static void InitializeValue(String ReqType,String testcase) throws Exception
		{
			 LoadPropertiesFile();
			 BookingTabName=(properties.getProperty("ENV").equalsIgnoreCase("TEST"))?"KeyStar Booking":"Five Star Booking";
			 AdminTabName=(properties.getProperty("ENV").equalsIgnoreCase("TEST"))?"KeyStar Admin":"Five Star Admin";
			 RefundTabName=(properties.getProperty("ENV").equalsIgnoreCase("TEST"))?"KeyStar Refund":"Five Star Refund";
			 SRdetailsTabName=(properties.getProperty("ENV").equalsIgnoreCase("TEST"))?"KeyStar SR Details":"Five Star SR Details";
			 FlightdetailsTabName=(properties.getProperty("ENV").equalsIgnoreCase("TEST"))?"KeyStar Flight Details":"Five Star Flight Details";	
			 
			 switch(ReqType.toUpperCase())
			 {
			 	case "EDIT":
			 		Editfivestardata = CommonMethods.getEditFiveStarData(testcase);
					Editflag=true;
					ReqNo=(properties.getProperty("EnvironmentUnderTest").equalsIgnoreCase("CERT"))?Editfivestardata.CERT.RequestNo:Editfivestardata.TSTS.RequestNo;
					pnrNumber=(properties.getProperty("EnvironmentUnderTest").equalsIgnoreCase("CERT"))?Editfivestardata.CERT.pnrNumber:Editfivestardata.TSTS.pnrNumber;
					OldReqNo=(properties.getProperty("EnvironmentUnderTest").equalsIgnoreCase("CERT"))?Editfivestardata.CERT.OldRequestNo:Editfivestardata.TSTS.OldRequestNo;
					ReqSource=Editfivestardata.RequestInitiation.ReqSource;
					arrFirstName = Editfivestardata.PassengerDetails.FirstName.split(",");
					arrLastName = Editfivestardata.PassengerDetails.LastName.split(",");
					arrPsngrType = Editfivestardata.PassengerDetails.PsngrType.split(",");
					PsngrType = Editfivestardata.PassengerDetails.PsngrType;
					Promocode = Editfivestardata.Airport.Promocode;
					selectadd = Editfivestardata.Airport.selectadd;
					arrPrimFlag = Editfivestardata.PassengerDetails.PrimFlag.split(",");
					arrAirportCode = Editfivestardata.Airport.AirportCode.split(",");
					arrServiceType = Editfivestardata.Airport.ServiceType.split(",");
					 arrPromoCertificateID = Editfivestardata.Airport.PromoCertificateID.split(",");
					arrPromocode = Editfivestardata.Airport.Promocode.split(",");
					 arrselectadd = Editfivestardata.Airport.selectadd.split(",");
					arrDateInterval = Editfivestardata.Airport.DateInterval.split(",");
					arrTimeInterval = Editfivestardata.Airport.TimeInterval.split(",");
					 EmailCheckBox=Editfivestardata.Email.EmailCheckBox;
				  		EmailAddress=Editfivestardata.Email.EmailAddress;
				  		ProfileID=Editfivestardata.creditCard.ProfileId	;
				  		CardFirstName=Editfivestardata.creditCard.CardFirstName	;
				  		CardLastName=Editfivestardata.creditCard.CardLastName;
				  		CardNumber=Editfivestardata.creditCard.CardNumber;
				  		CardExpMonth=Editfivestardata.creditCard.CardExpMonth;
				  		CardExpYear=Editfivestardata.creditCard.CardExpYear;
				  		BookPriority=Editfivestardata.ConceirgeKey.BookPriority;
				  		TransferRefundPNRNo = Editfivestardata.TransferRefund.Refundpnr.toString();
				  		TransferRefundReqNo = Editfivestardata.TransferRefund.RefundReqNo.toString();
				  		arrAirportPrice=Editfivestardata.Airport.AirportPrice.split(",");
				  		NetTotalAmt = Double.parseDouble(Editfivestardata.Payment.NetTotalAmt);
						PromoDiscount = Double.parseDouble(Editfivestardata.Payment.PromoDiscount);
						NetAdultPrice = Double.parseDouble(Editfivestardata.Payment.AdultPrice);
						OutstandingAmt = Double.parseDouble(Editfivestardata.Payment.OutStandingAmt);
						SRBookingStatus=Editfivestardata.Airport.SRBookingStatus;
						arrSRBookingStatus=Editfivestardata.Airport.SRBookingStatus.split(",");
						arrNetTotalAmt=Editfivestardata.Payment.NetTotalAmt.split(",");
						BookingStatus=Editfivestardata.RequestInitiation.FivestarBookingStatus; 
						UpdatedBookingStatus=Editfivestardata.RequestInitiation.FivestarUpdatedBookingStatus; 
					//	NetTotalAmt=Editfivestardata.Payment.NetTotalAmt;
						arrOutstandingAmt=Editfivestardata.Payment.OutStandingAmt.split(",");
						AirportCode=Editfivestardata.Airport.AirportCode;
						RefundAmt=Editfivestardata.Payment.RefundAmt;
						arrCancelledSRStatus=Editfivestardata.Airport.CancelledSRStatus.split(",");
						arrDiscountdoller=Editfivestardata.Promotions.Discountdoller.split(",");
						arrDiscountpercent=Editfivestardata.Promotions.Discountpercent.split(",");
						AirportCodeAdditionService=Editfivestardata.AdditionalServices.AirportCode;
					 	ServiceTypeAdditionService=Editfivestardata.AdditionalServices.ServiceType;
					 	PriceperBookingAdditionService=Editfivestardata.AdditionalServices.PriceperBooking;
					 	AdultPriceAdditionService=Editfivestardata.AdditionalServices.AdultPrice;
					 	ChildPriceAdditionService=Editfivestardata.AdditionalServices.ChildPrice;
					 	TotalAdditionalServices=Editfivestardata.AdditionalServices.TotalAdditionalServices;
						break;
			 	case "BOOK":
			 		BookFivestardata = CommonMethods.getBookFivestarData(testcase);
					ReqNo=(properties.getProperty("EnvironmentUnderTest").equalsIgnoreCase("CERT"))?BookFivestardata.CERT.RequestNo:BookFivestardata.TSTS.RequestNo;
					pnrNumber=(properties.getProperty("EnvironmentUnderTest").equalsIgnoreCase("CERT"))?BookFivestardata.CERT.pnrNumber:BookFivestardata.TSTS.pnrNumber;
					OldReqNo="";
					ReqSource=BookFivestardata.RequestInitiation.ReqSource;
					arrFirstName = BookFivestardata.PassengerDetails.FirstName.split(",");
					arrLastName = BookFivestardata.PassengerDetails.LastName.split(",");
					arrPsngrType = BookFivestardata.PassengerDetails.PsngrType.split(",");
					arrPrimFlag = BookFivestardata.PassengerDetails.PrimFlag.split(",");
					arrAirportCode = BookFivestardata.Airport.AirportCode.split(",");
					arrServiceType = BookFivestardata.Airport.ServiceType.split(",");
					 arrPromoCertificateID = BookFivestardata.Airport.PromoCertificateID.split(",");
					arrPromocode = BookFivestardata.Airport.Promocode.split(",");
					 arrselectadd = BookFivestardata.Airport.selectadd.split(",");
					arrDateInterval = BookFivestardata.Airport.DateInterval.split(",");
					arrTimeInterval = BookFivestardata.Airport.TimeInterval.split(",");
					 PsngrType = BookFivestardata.PassengerDetails.PsngrType;
						Promocode = BookFivestardata.Airport.Promocode;
						selectadd = BookFivestardata.Airport.selectadd;
						Bookingflag=true;
					 EmailCheckBox=BookFivestardata.Email.EmailCheckBox;
				  		EmailAddress=BookFivestardata.Email.EmailAddress;
				  		ProfileID=BookFivestardata.creditCard.ProfileId	;
				  		CardFirstName=BookFivestardata.creditCard.CardFirstName	;
				  		CardLastName=BookFivestardata.creditCard.CardLastName;
				  		CardNumber=BookFivestardata.creditCard.CardNumber;
				  		CardExpMonth=BookFivestardata.creditCard.CardExpMonth;
				  		CardExpYear=BookFivestardata.creditCard.CardExpYear;
				  		BookPriority=BookFivestardata.ConceirgeKey.BookPriority;
				  		TransferRefundPNRNo = BookFivestardata.TransferRefund.Refundpnr.toString();
				  		TransferRefundReqNo = BookFivestardata.TransferRefund.RefundReqNo.toString();
				  		arrAirportPrice=BookFivestardata.Airport.AirportPrice.split(",");
				  		NetTotalAmt = Double.parseDouble(BookFivestardata.Payment.NetTotalAmt);
						PromoDiscount = Double.parseDouble(BookFivestardata.Payment.PromoDiscount);
						NetAdultPrice = Double.parseDouble(BookFivestardata.Payment.AdultPrice);
						OutstandingAmt=Double.parseDouble(BookFivestardata.Payment.OutStandingAmt);
						SRBookingStatus=BookFivestardata.Airport.SRBookingStatus;
						arrSRBookingStatus=BookFivestardata.Airport.SRBookingStatus.split(",");
						arrNetTotalAmt=BookFivestardata.Payment.NetTotalAmt.split(",");
						BookingStatus=BookFivestardata.RequestInitiation.FivestarBookingStatus; 
					//	NetTotalAmt=BookFivestardata.Payment.NetTotalAmt;
						arrOutstandingAmt=BookFivestardata.Payment.OutStandingAmt.split(",");
						AirportCode=BookFivestardata.Airport.AirportCode;
						TransferRefundAmt=BookFivestardata.TransferRefund.RefundAmt;
						arrDiscountdoller=BookFivestardata.Promotions.Discountdoller.split(",");
						arrDiscountpercent=BookFivestardata.Promotions.Discountpercent.split(",");
						AirportCodeAdditionService=BookFivestardata.AdditionalServices.AirportCode;
					 	ServiceTypeAdditionService=BookFivestardata.AdditionalServices.ServiceType;
					 	PriceperBookingAdditionService=BookFivestardata.AdditionalServices.PriceperBooking;
					 	AdultPriceAdditionService=BookFivestardata.AdditionalServices.AdultPrice;
					 	ChildPriceAdditionService=BookFivestardata.AdditionalServices.ChildPrice;
					 	TotalAdditionalServices=BookFivestardata.AdditionalServices.TotalAdditionalServices;
						break;
			 	case "CANCEL":
					CancelBookingdata = CommonMethods.getCancelBookingData(testcase);
					Cancelflag=true;
					ReqNo=(properties.getProperty("EnvironmentUnderTest").equalsIgnoreCase("CERT"))?CancelBookingdata.CERT.RequestNo:CancelBookingdata.TSTS.RequestNo;
					pnrNumber=(properties.getProperty("EnvironmentUnderTest").equalsIgnoreCase("CERT"))?CancelBookingdata.CERT.pnrNumber:CancelBookingdata.TSTS.pnrNumber;
					OldReqNo=(properties.getProperty("EnvironmentUnderTest").equalsIgnoreCase("CERT"))?CancelBookingdata.CERT.UpdatedRequestNo:CancelBookingdata.TSTS.UpdatedRequestNo;
					ReqSource=CancelBookingdata.RequestInitiation.ReqSource;
					arrFirstName = CancelBookingdata.PassengerDetails.FirstName.split(",");
					arrLastName = CancelBookingdata.PassengerDetails.LastName.split(",");
					arrPsngrType = CancelBookingdata.PassengerDetails.PsngrType.split(",");
					PsngrType = CancelBookingdata.PassengerDetails.PsngrType;
					Promocode = CancelBookingdata.Airport.Promocode;
					selectadd = CancelBookingdata.Airport.selectadd;
					arrPrimFlag = CancelBookingdata.PassengerDetails.PrimFlag.split(",");
					arrAirportCode = CancelBookingdata.Airport.AirportCode.split(",");
					arrServiceType = CancelBookingdata.Airport.ServiceType.split(",");
					 arrPromoCertificateID = CancelBookingdata.Airport.PromoCertificateID.split(",");
					arrPromocode = CancelBookingdata.Airport.Promocode.split(",");
					 arrselectadd = CancelBookingdata.Airport.selectadd.split(",");
					arrDateInterval = CancelBookingdata.Airport.DateInterval.split(",");
					arrTimeInterval = CancelBookingdata.Airport.TimeInterval.split(",");
					 EmailCheckBox=CancelBookingdata.Email.EmailCheckBox;
				  		EmailAddress=CancelBookingdata.Email.EmailAddress;
				  		ProfileID=CancelBookingdata.creditCard.ProfileId	;
				  		CardFirstName=CancelBookingdata.creditCard.CardFirstName	;
				  		CardLastName=CancelBookingdata.creditCard.CardLastName;
				  		CardNumber=CancelBookingdata.creditCard.CardNumber;
				  		CardExpMonth=CancelBookingdata.creditCard.CardExpMonth;
				  		CardExpYear=CancelBookingdata.creditCard.CardExpYear;
				  		BookPriority=CancelBookingdata.ConceirgeKey.BookPriority;
				  		TransferRefundPNRNo = CancelBookingdata.TransferRefund.Refundpnr.toString();
				  		TransferRefundReqNo = CancelBookingdata.TransferRefund.RefundReqNo.toString();
				  		arrAirportPrice=CancelBookingdata.Airport.AirportPrice.split(",");
				  		NetTotalAmt = Double.parseDouble(CancelBookingdata.Payment.NetTotalAmt);
						PromoDiscount = Double.parseDouble(CancelBookingdata.Payment.PromoDiscount);
						NetAdultPrice = Double.parseDouble(CancelBookingdata.Payment.AdultPrice);
						OutstandingAmt = Double.parseDouble(CancelBookingdata.Payment.OutStandingAmt);
						SRBookingStatus=CancelBookingdata.Airport.SRBookingStatus;
						arrSRCancelledBookingStatus = CancelBookingdata.Airport.SRCancelledBookingStatus.split(",");
						arrSRBookingStatus=CancelBookingdata.Airport.SRBookingStatus.split(",");
						arrNetTotalAmt=CancelBookingdata.Payment.NetTotalAmt.split(",");
						BookingStatus=CancelBookingdata.RequestInitiation.FivestarBookingStatus; 
					//	NetTotalAmt=CancelBookingdata.Payment.NetTotalAmt;
						arrOutstandingAmt=CancelBookingdata.Payment.OutStandingAmt.split(",");
						AirportCode=CancelBookingdata.Airport.AirportCode;
						RefundAmt=CancelBookingdata.Payment.RefundAmt;
						arrDiscountdoller=CancelBookingdata.Promotions.Discountdoller.split(",");
						arrDiscountpercent=CancelBookingdata.Promotions.Discountpercent.split(",");
						AirportCodeAdditionService=CancelBookingdata.AdditionalServices.AirportCode;
					 	ServiceTypeAdditionService=CancelBookingdata.AdditionalServices.ServiceType;
					 	PriceperBookingAdditionService=CancelBookingdata.AdditionalServices.PriceperBooking;
					 	AdultPriceAdditionService=CancelBookingdata.AdditionalServices.AdultPrice;
					 	ChildPriceAdditionService=CancelBookingdata.AdditionalServices.ChildPrice;
					 	TotalAdditionalServices=CancelBookingdata.AdditionalServices.TotalAdditionalServices;
						break;
			 		case "CREDITCARD":
			 			Creditcarddata=CommonMethods.getCreditcardData(testcase);
			 			CardNum = Creditcarddata.CreditCardProfile.CardNum;
			 			AADVNum = Creditcarddata.CreditCardProfile.AADVNum;
			 			OnewordId = Creditcarddata.OnewordId;		 	
			 }
			 
		}	   
}
